[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_program = "8ymbn5nw6fKBEeWoSo1dfMZH45jrotvsmv4UCZnFFUfa"
market_program = "9iCxo1nJnDCtZTyKqFKc5PCFmfiezNnXCnycCrYq1GVL"
oracle_adapter = "CKGRJrwnWayKCAUzYvhF67eHkyD45uKFd8p8dYaXQ742"
oracle_adapter_contract = "6QAq31696E4a8PKMgzVrTq1uBzvF87JNTeAQyHmGivEJ"
prediction_market = "6rhwmqAZGHZhePX15dDRjrAtXNx4GcLS2XM1cVXmHBe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"
